name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@master
      
      # Connect or Create the Azure Machine Learning Workspace
      - name: Connect/Create Azure Machine Learning Workspace
        id: aml_workspace
        uses: Azure/aml-workspace@master
        with:
            azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Self test
        id: selftest
        uses: ashishonce/amlrun2@master
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
        continue-on-error: true
